### ISSUE TITLE
Cannot create references to/from string offsets

### ISSUE THREAD

**Issue by cAstraea** [illuminatech/multipart-middleware#3]
### What steps will reproduce the problem?
I'm trying to reproduce it
### What is the expected result?
no error
### What do you get instead?
error
### Additional info

| Q                         | A
| ------------------------- | ---
| This Package Version      | latest
| Laravel Framework Version | 9.52
| PHP version               |  8.1
| Operating system          |

Seems I'm having some strange issue not sure what's wrong think the request might be off.
Cannot create references to/from string offsets on the addValue() function 
$current = &$current[$namePart];
![image](https://github.com/illuminatech/multipart-middleware/assets/13070662/ce1025ca-f441-4212-b5cc-b6c9e85cf4d4)

**Comment by klimov-paul** [comment]
Closed, until steps to reproduce are provided.
